{% set name = "PennyLane" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3fed3689fe8b2a8c35f38d679489d40731b1d3fd2683a783df9627ca79def575

build:
  number: 0
  noarch: python
  entry_points:
    - pl-device-test=pennylane.devices.tests:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - appdirs
    - autograd
    - autoray
    - cachetools
    - networkx
    - numpy
    - pennylane-lightning >=0.18
    - python >=3.7
    - scipy
    - semantic_version ==2.6
    - toml

test:
  imports:
    - pennylane
    - pennylane.beta
  commands:
    - pip check
    - pl-device-test --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/PennyLaneAI/pennylane
  summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
  license: Apache-2.0 AND MIT
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
